<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 7/4/2022
 * Time: 15:29
 */

namespace App\Utils\Caches;


use App\Models\CompanyInformation;
use App\Repository\CompanyInformationRepositoryInterface;

class CompanyInformationUtil extends AbstractCacheDataUtil
{

    /**
     * @return CompanyInformationUtil
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct('company_information', CompanyInformationRepositoryInterface::class, CompanyInformation::class);
    }

}