<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 7/4/2022
 * Time: 15:29
 */

namespace App\Utils\Caches;


use App\Models\Language;
use App\Repository\LanguageRepositoryInterface;

class LanguageUtil extends AbstractCacheDataUtil
{

    /**
     * @return LanguageUtil
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct('languages', LanguageRepositoryInterface::class, Language::class);
    }


}