<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 7/4/2022
 * Time: 15:28
 */

namespace App\Utils\Caches;


use App\Common\Exceptions\ObjectInvalidCastException;
use App\Models\MenuPosition;
use App\Repository\MenuPositionRepositoryInterface;

class MenuUtil extends AbstractCacheDataUtil
{

    /**
     * @return MenuUtil
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct('menus', MenuPositionRepositoryInterface::class, MenuPosition::class);
    }

    /**
     * @throws ObjectInvalidCastException
     */
    public function loadCacheData()
    {
        if ($this->repository instanceof MenuPositionRepositoryInterface) {
            $models = $this->repository->get([], 'id:asc', ['menus.children']);
            foreach ($models as $model) {
                if ($model instanceof MenuPosition) {
                    $menus = [];
                    foreach ($model->menus as $m) {
                        array_push($menus, $m->toArray());
                    }
                    $this->data[$model->name] = $menus;
                } else {
                    throw new ObjectInvalidCastException(MenuPosition::class);
                }
            }
        } else {
            throw new ObjectInvalidCastException(MenuPositionRepositoryInterface::class);
        }
    }

}