<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 7/4/2022
 * Time: 15:28
 */

namespace App\Utils\Caches;


use App\Common\Exceptions\ObjectInvalidCastException;
use App\Common\WhereClause;
use App\Repository\ProductVariantRepositoryInterface;
use App\Models\ProductVariant;

class VariantUtil extends AbstractCacheDataUtil
{
    /**
     * @return VariantUtil
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct('product_variants', ProductVariantRepositoryInterface::class, ProductVariant::class);
    }
    public function getVariant($id)
    {
        $variants = $this->repository->get([WhereClause::query('product_id',$id)], 'id:asc',[]);
        return $variants;

    }
    public function getNameVariantById($id)
    {
        $variants = $this->repository->get([WhereClause::query('id',$id)], 'id:asc',[])->first();
        return $variants->name;

    }

}
