<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 11/5/2022
 * Time: 15:30
 */

namespace App\Utils;


use App\Common\SingletonPattern;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Session;

class AffiliateUtil extends SingletonPattern
{
    protected $keyCookie;
    protected $ttl;

    protected function __construct()
    {
        $this->keyCookie = 'eziAffData';
        $this->ttl = 7 * 24 * 60;
    }

    /**
     * @return AffiliateUtil
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }


    private function saveSessionId()
    {
        Session::flash('eziAffSessionId', Session::getId());
    }

    private function getSessionId()
    {
        return Session::get('eziAffSessionId', null);
    }

    private function overrideData(array $affiliateData)
    {
        if (empty($affiliateData)) {
            return;
        }
        $savedData = array_merge($this->getData(), $affiliateData);
        Cookie::queue($this->keyCookie, http_build_query($savedData), $this->ttl);
    }

    public function saveData(array $affiliateData)
    {
        if (empty($affiliateData)) {
            $this->clearData();
        } else {
            Cookie::queue($this->keyCookie, http_build_query($affiliateData), $this->ttl);
        }
    }

    public function getData()
    {
        $value = Cookie::get($this->keyCookie);
        if (isset($value)) {
            parse_str($value, $params);
            return $params;
        }
        return [];
    }

    public function clearData()
    {
        Cookie::queue(Cookie::forget($this->keyCookie));
    }

    public function saveRequest(Request $request)
    {
        if (!$request->isMethod('get')) {
            return;
        }
        if ($request->ajax()) {
            return;
        }
        $refererUrl = $request->headers->get('referer');
        $query = $request->query();
        if (empty($refererUrl)) {
            //truy cap truc tiep
            return;
        } else {
            //truy cap qua link
            $sessionId = $this->getSessionId();
            if (isset($sessionId) && $sessionId == Session::getId()) {
                //van cung session
                $this->overrideData($query);
            } else {
                //ghi lai affliliate data
                $this->saveData($query);
            }
            $this->saveSessionId();
        }

    }

}