<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 8/19/2022
 * Time: 15:56
 */

namespace App\Utils;


use App\Common\SingletonPattern;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CdnUtil extends SingletonPattern
{
    /* @var $disk Storage */
    protected $disk;

    protected $rootDir;
    protected $rootUrl;

    /**
     * CdnUtil constructor.
     */
    public function __construct()
    {
        $this->rootUrl = config('cdn.url');
    }

    /**
     * @return CdnUtil
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function getCompressedImageURL(string $imageURL)
    {
        if (Str::startsWith($this->rootUrl, $imageURL)) {
            $ext = pathinfo($imageURL, PATHINFO_EXTENSION);
            if (Str::endsWith($imageURL, ".$ext")) {
                return Str::replaceLast(".$ext", ".min.$ext", $imageURL);
            }
        }
        return $imageURL;
    }
}
