<?php
/**
 * Created by PhpStorm.
 * User: BaoHoang
 * Date: 10/28/2022
 * Time: 19:06
 */

namespace App\Common\Config;


class ManualPayConfig extends AbstractPayConfig
{
    protected $accounts;

    /**
     * @return ManualPayConfig
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function __construct(array $config)
    {
        parent::__construct('Chuyển khoản', ['accounts'], $config);
    }

    /**
     * @return mixed
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    protected function check($key, $config)
    {
        if ($key != 'accounts') {
            parent::check($key, $config);
            return;
        }
        if (!array_key_exists('accounts', $config)) {
            throw new \Exception("Cấu hình $this->method chưa đặt giá trị accounts");
        } else {
            $accounts = $config['accounts'];
            $this->accounts = [];
            foreach ($accounts as $a) {
                array_push($this->accounts, new AccountConfig($a));
            }
        }
    }

}